@startuml torneoDeMagos

abstract class Participante {
    poderTotal()
    esVencidoPor(unParticipante)
    desafiar(unParticipante)
    ganarEnergiaMagica(unaCantidad)
    perderAnte(unParticipante)
}

class Mago {
    nombre
    poderInnato
    resistenciaMagica
    energiaMagica
    objetosMagicos
    categoria
    --
    poderTotal()
    esVencidoPor(unParticipante)
    perderEnergiaMagica(unPorcentaje)
    ganarEnergiaMagica(unaCantidad)
    perderAnte(unParticipante)
}

class Gremio {
    miembros
    --
    poderTotal()
    energiaMagica()
    resistenciaMagica()
    esVencidoPor(unParticipante)
    miembroLider()
    ganarEnergiaMagica(unaCantidad)
    perderAnte(unParticipante)
}

interface Categoria {
    esVencidoPor(atacado, atacante)
}

class CategoriaMortal {
    multiplicadorDeResistencia
    porcentajeDePerdida
    --
    esVencidoPor(atacado, atacante)
    transferirEnergiaMagica(atacado, atacante)
}

object inmortal {
    esVencidoPor(atacado, atacante)
}

interface ObjetoMagico {
    poderAportado(unMago)
}

abstract class ObjetoMagicoConPoderBase {
    poderBase
    --
    poderAportado(unMago)
    poderExtra(unMago)
}

class Varita {
    poderExtra(unMago)
}

class Tunica {
    poderExtra(unMago)
}

class TunicaEpica {
    poderExtra(unMago)
}

class Amuleto {
    poderAportado(unMago)
}

object ojota {
    poderAportado(unMago)
}

Mago -u-|> Participante
Gremio -u-|> Participante
Gremio -> "*" Mago

Mago --> "*" ObjetoMagico
Mago --> Categoria

Amuleto .u.|> ObjetoMagico
ojota .u.|> ObjetoMagico
ObjetoMagicoConPoderBase .u.|> ObjetoMagico

Varita -u-|> ObjetoMagicoConPoderBase
Tunica -u-|> ObjetoMagicoConPoderBase
TunicaEpica -u-|> Tunica

CategoriaMortal .u.|> Categoria
inmortal .u.|> Categoria

@enduml